### ISSUE TITLE
resolution to rescale seabed classification raster

### ISSUE THREAD

**Issue by dwwolfson** [dwwolfson/red_snapper#1]
Do people have any thoughts on the best cell size to use? Tried to look for specific advise in Hanks paper but didn't find it. I seem to remember that they suggested making cell size big enough that multiple steps often occur to make the use of residence time more applicable.

We should probably ask the NOAA folks as well.

**Comment by jfieberg** [comment]
Good question. I think it makes sense to pick a scale where transitions
occur, but I don't have a good sense for how large the transition rates
should be to aid in the estimation process.  It might be worth contacting
one of the authors for guidance?  Or, try out a few different sizes and see
what impact it has on the analysis.

John
-------------------------------------------------------------------------
John Fieberg
Associate Professor of Quantitative Ecology
Department of Fisheries, Wildlife, Conservation Biology
University of Minnesota
Phone:  612-301-7132
https://fieberg-lab.cfans.umn.edu/
He, Him, His
-------------------------------------------------------------------------

**Comment by dwwolfson** [comment]
Moving ahead with 10m x 10m for now. It's quick and easy to aggregate to pretty much whatever we want because the original raster is 1 meter by 1 meter.

Currently at a standstill because converting to glm data requires a gradient raster, which I assume means a continuous covariate. Not sure why this is a requirement, anyone else?

**Comment by dwwolfson** [comment]
I misinterpreted that last comment. Everything seemed to run ok. I aggregated the raster using the mean of the values at first but then figured out that using the mode of the 10 cells made the most sense.
